image: node
stages:
  - build
  - test
cache:
  key: master
  paths:
    - node_modules/

build:
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - ./build

test:
  stage: test
  script:
    - npm install
    - npm run test-dev