stages:
  - build
  - test

build:
  stage: build
  image: node
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - ./build

test:
  stage: test
  script:
    - npm run test-dev